import { useEffect, useState } from "react";
import API from "../services/api";

function Reports() {

  const [reports, setReports] =
    useState([]);

  useEffect(() => {

    fetchReports();

  }, []);

  const generateReport =
  async () => {

    try {

      await API.post(
        "/reports/generate"
      );

      alert(
        "Report Generated"
      );

      fetchReports();

    } catch (error) {

      alert(
        error.response?.data?.message ||
        "Failed"
      );

    }

  };

  const fetchReports =
  async () => {

    try {

      const res =
      await API.get(
        "/reports/all"
      );

      setReports(
        res.data
      );

    } catch (error) {

      console.log(error);

    }

  };

  return (

    <div className="page-container">

      <h1>
        Reports
      </h1>

      <button
        className="report-btn"
        onClick={generateReport}
        >
        Generate Report
        </button>
        
      <div className="courses-grid">

        {reports.map((report) => (

          <div
            key={report._id}
            className="analytics-card"
          >

            <h2>
              Report
            </h2>

            <p>
              Users:
              {report.totalUsers}
            </p>

            <p>
              Courses:
              {report.totalCourses}
            </p>

            <p>
              Enrollments:
              {report.totalEnrollments}
            </p>

            <p>
              Revenue:
              ₹{report.totalRevenue}
            </p>

            <p>
              Generated By:
              {" "}
              {report.generatedBy?.name}
            </p>

          </div>

        ))}

      </div>

    </div>

  );

}

export default Reports;